# Generated by Django 5.2.7 on 2026-05-20 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='account_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='transaction',
            name='bank_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='bank_type',
            field=models.CharField(blank=True, choices=[('jazzcash', 'JazzCash'), ('easypaisa', 'Easypaisa'), ('bank_transfer', 'Bank Transfer'), ('other', 'Other')], default='', max_length=20),
        ),
    ]
