# Generated by Django 5.2.7 on 2026-05-20 09:53

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='earning_per_video',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount credited to user wallet per completed video watch.', max_digits=8),
        ),
    ]
