# Generated by Django 4.2.8 on 2026-05-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterSignupCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Global registration code required for new users.', max_length=100)),
            ],
            options={
                'verbose_name': 'Master Registration Code',
                'verbose_name_plural': 'Master Registration Code',
            },
        ),
    ]
